[workspace]
members = [
  "."
]

[tasks]
lint = { parallel = true }
test = { parallel = true }
build = { parallel = true }

[defaults.go.tasks]
lint = "golangci-lint run ./..."
test = "go test -race ./..."
build = "go build ./..."

